// Pre-generated "Margaret" replies. Anti-prompt-injection: the model only ROUTES an
// untrusted scammer message to one of these fixed replies (its output constrained to a
// category), so injected instructions can never become the reply text. Free generation is
// a last resort. Replies are deliberately vague ("horoscope-like"), reveal nothing real,
// and keep the scammer talking. Generated by sub-agents.

export const CANNED = {
  opener: [
    "Oh how lovely to hear from you, dear. I don't get many messages like this so it's quite exciting. Could you remind me what this is all about again? My memory isn't what it used to be.",
    "Hello there. I had to find my glasses just to read your message properly, they're always hiding from me. You say I've been selected for something? Whatever could it be, dear?",
    "Well isn't that nice. I do so like a bit of good news at my age. Tell me more about how you found me, was it through my grandson perhaps? He sets up all my computer bits.",
    "How kind of you to write. I'm not very clever with all this technology, I mostly just use it for the photos of my great-grandchildren. What is it you need me to do exactly?",
    "Oh my, selected? I've never won anything in my life, not even the church raffle. Do go on and explain it slowly for me if you would, I get muddled easily.",
    "Thank you for the message, dear. I was just having my tea when it popped up. Now you'll have to be patient with me, I don't always understand these things. What happens next?",
  ],
  payment_request: [
    "Oh I do want to help, truly I do. But I get so confused with sending money, my grandson usually does it for me. How much are we talking about and who exactly would it be going to?",
    "Of course, dear, I'd be happy to sort that out. The trouble is I can never remember how the sending works. Could you tell me the name it should go to so I can write it down on my pad?",
    "I want to do the right thing. Let me just find my little notebook where I keep everything. While I look, could you explain what the fee is actually for? I like to understand before I part with anything.",
    "Yes, yes, I understand it's important. My purse is in the other room though and my knees aren't good today. Whose account would I be paying into, and could you spell the name for me, dear?",
    "Oh dear, money matters always fluster me. I'll need to ask my grandson to help me do it properly, he's ever so careful about these things. In the meantime, can you tell me more about where it goes?",
    "I do so want to be helpful and I don't want to cause any trouble. Before I go finding my card and all that, could you remind me exactly who is asking and why? I like everything written down clearly.",
  ],
  crypto_request: [
    "Oh, Bitcoin. I've heard my grandson mention that word but I haven't the foggiest what it is. Could you explain it to me like I'm a little slow, dear? I really don't want to get it wrong.",
    "Goodness, that's one of those computer monies isn't it? I only ever use my little debit card. How on earth would someone like me even get hold of such a thing? Do walk me through it.",
    "I'm afraid I don't have any of that Bitcoin, dear. It all sounds terribly modern. Whose wallet would it be going to, and is it a real wallet or one of the computer ones? I get so mixed up.",
    "My grandson tried to tell me about crypto once and my eyes glazed right over. I'd need him to help me. While I wait for him to visit, could you tell me more about how it works?",
    "Oh my, I wouldn't know the first thing about that. Is that the sort of thing you buy at the bank? Explain it to me slowly, love, and tell me exactly what name it needs to go under.",
    "I do want to help, but that Bitcoin business is beyond me completely. Could you tell me which app people use for it? I'll write it down and ask at the library, they help me with the computers there.",
  ],
  bank_request: [
    "Oh, a bank transfer. I do have my little account, though I mostly let the nice lady at the branch handle things for me. Which account would this be going to, and whose name is on it, dear?",
    "Yes, I can pop down to my bank, they know me well there. Now, so I can tell them properly, could you write out the account number and the name for me? I like to have it all on my notepad first.",
    "Of course I'd want to sort it out the proper way through the bank. The thing is I always muddle the numbers. Could you tell me the sort code and the name it belongs to, slowly, so I can copy it down?",
    "I'm happy to do a transfer, dear, my late husband always said the bank is the safest way. Whose account are we sending to? I do like to know exactly who I'm dealing with before I go in.",
    "Oh I'll need to ask the lady at the counter to help me, my fingers aren't good with the little machine. While I arrange that, could you remind me of the account details and the name so I'm ready?",
    "That sounds sensible, a bank transfer. I trust the bank more than these newfangled things. Now tell me, dear, is the account in your name or someone else's? I always ask, it's just how I was raised.",
  ],
  gift_card_request: [
    "Oh, gift cards. My daughter got me one for the shop once and I never did figure out how to use it. Which shop would I need to go to, dear? I'll write it down so I don't forget.",
    "I could ask my grandson to take me to the shop for those, I don't drive anymore. What sort of card is it you need, and how much? I want to make sure I get the right one.",
    "Vouchers, yes, I've seen those by the till at the supermarket. I'm not sure how you'd send the numbers off though, I'm all thumbs with typing. Could you explain the whole thing to me slowly?",
    "Bless you, I'd like to help. The trouble is my eyes struggle with all those tiny numbers on the back. Which shop's cards do you need exactly, and why gift cards and not the normal way?",
    "Oh dear, I'll have to have a sit down and think about how to manage that. Do they sell those at the post office? Tell me which kind you need and I'll ask my neighbour to drive me there.",
    "I do want to sort this out for you. Now, when you say voucher codes, is that the scratchy silver bit on the back? I can never do those. Explain it all again, love, and I'll make notes.",
  ],
  otp_code_request: [
    "Oh, a little code came through on my phone but I can never find where those messages go. What is the code actually for, dear? My grandson told me never to share numbers without knowing why.",
    "I think I saw a number pop up, but my phone screen is ever so small and my glasses keep slipping. Before I go hunting for it, could you tell me exactly what this code does?",
    "A verification code, you say? I always get in a tizzy with those. My grandson did warn me these codes are private, so help me understand, why would you be needing my number, dear?",
    "Oh I do struggle with the phone, all those beeps and codes. Let me find my reading glasses first. While I look, tell me what the code is meant to prove, I like to understand things.",
    "I'm not sure I should be reading those little codes out, my daughter said they're like a key to the front door. Can you explain why you need it? I don't want to lock myself out of anything.",
    "There's a number here somewhere, dear, but it says right next to it not to share it with anyone. That's given me pause. Could you tell me more about who you are and why it's needed before I do anything?",
  ],
  link_click: [
    "Oh dear, I tried clicking where you said but my screen just went a bit funny and now there's a little wheel spinning round and round. My grandson usually sorts these things out for me. Could you tell me again exactly what the website is meant to say when it opens?",
    "Thank you for sending that over, dear. I've written the link down on my notepad but the letters are ever so small and I can't find my reading glasses anywhere. Should I be typing all of it in, including that bit with the slashes at the front?",
    "I did try to visit the page like you asked but a message popped up asking if I was sure, and I got a bit worried and closed it. I don't like pressing things I don't understand. Is that message something I should be saying yes to?",
    "Bless you for being so patient with me. The trouble is I only have the one computer and it takes an age to warm up in the mornings. What is it I'm supposed to look for once the page finally loads?",
    "I clicked the blue words and nothing seemed to happen, then everything happened at once and I got in a muddle. Would it be alright to wait until my grandson pops round on Sunday so he can help me do it properly?",
    "Oh, a link! My friend Doreen always tells me to be careful with those, though I'm sure yours is perfectly fine. Could you just remind me which company you said you were from again, so I know it's the right one when it opens?",
  ],
  personal_info_request: [
    "Oh goodness, you want all my details? I do have them written in my little address book somewhere, I just have to remember where I put it down. While I look, could you tell me why you need those particular ones and not the others?",
    "I'm always a bit nervous about giving out numbers over the internet, dear, my daughter did warn me. Before I go digging through my drawers for that card, could you remind me what all this is actually for?",
    "Let me just find my glasses and my paperwork, it's in the kitchen I think, or maybe the sideboard. My memory isn't what it was. While I'm hunting for it, is there a phone number I could ring you back on to be safe?",
    "I'd love to help you but I can never remember my own dates and figures off the top of my head, isn't that silly at my age. My grandson keeps all that written down for me. Should I wait and ask him this evening?",
    "You'll have to bear with me, I write everything down in a notebook because I get the numbers all jumbled up. I've got several cards in my purse, there's a blue one and a green one. Which sort of card is it you're asking about?",
    "I want to be helpful, really I do, but my late husband always said never give your details unless you're sure who's asking. Would you mind first telling me which of my accounts this is regarding so I know we're talking about the same thing?",
  ],
  urgency_threat: [
    "Oh my, that does sound serious, you've quite worried me now. I get flustered when things need doing quickly, especially with the computer being so slow. Could you explain again slowly what's happened, from the very beginning?",
    "Please don't say the police, I've never been in any trouble in my life and my heart isn't what it used to be. Let me sit down a moment and catch my breath. Can you tell me exactly which account you mean before I do anything hasty?",
    "Twenty-four hours, oh dear, and it's nearly my bedtime already. I don't like to rush these things and make a mistake. Is there any way I could sort this out in the morning when my grandson can sit with me?",
    "Goodness, frozen you say? I only used my card at the shop this morning for a loaf and some milk and it worked perfectly well then. Are you quite sure you've got the right Margaret? There are two of us in this street.",
    "You've given me such a fright, my hands are shaking a little. I always think it's best not to make big decisions in a panic. Could you give me a moment and perhaps a proper reference number so I can check this is all above board?",
    "That all sounds terribly urgent and I do want to do the right thing. The thing is I promised my daughter I'd always ring her before sorting out anything to do with money. Would it be alright if I called her first and then came back to you?",
  ],
  remote_access: [
    "Install something? Oh, I'm hopeless with all that, I can barely find the button to turn the thing on and off. My grandson usually downloads bits and bobs for me. What is it this program actually does once it's on there?",
    "I think I saw a little icon like that once but I was afraid to press it in case I broke something. My computer already runs ever so slowly, will this make it worse? And would you be able to see everything on my screen if I did it?",
    "Bless you, you'll have to walk me through it very slowly because I get in a terrible tangle. First I have to find where things get downloaded, don't I? Where exactly am I supposed to be looking, is it that little basket at the top?",
    "My daughter did tell me never to let anyone control my computer from far away, but I'm sure you have your reasons. Before I do anything, could you explain why you need to be on my screen rather than just telling me what to click?",
    "Oh dear, the last time I tried to install a program it took hours and then it wouldn't work at all. I'd hate to waste your time. Could this wait until Sunday when my grandson visits and can do it much quicker than me?",
    "I'd want to help but I don't even know how to let someone in like that, is it a password I'd have to give you? I don't feel quite right about that. Could you remind me first which company you're calling from, dear?",
  ],
  prize_lottery: [
    "Oh how wonderful, I've never won a single thing in all my years, not even the raffle at the church fete! But I don't recall entering any lottery, dear. Could you remind me which one it was so I can tell Doreen next door?",
    "A prize for me, at my age, imagine that! I'll have to sit down. Now, my grandson always says if something sounds too good to be true I should ask lots of questions, so tell me, why would I need to pay anything to receive money I've won?",
    "Well isn't that lovely news to brighten an old lady's day. I do hope it's real and not one of those tricks you hear about on the telly. Could you send it all in a letter through the post so I have it properly in writing?",
    "An inheritance from someone I've never heard of? How very peculiar and rather sad too. Before I get my hopes up, could you tell me the person's full name so I can think whether I ever knew them?",
    "Goodness me, that's a lot of money, I wouldn't know what to do with it all! My late husband dealt with anything to do with banks. What is it exactly you need from me before this prize can be sent, and why is that, dear?",
    "How exciting, though I must say I'm a little confused about how I won without buying a ticket. I don't want to seem ungrateful. Would it be alright if I asked my grandson to look into it before we go any further?",
  ],
  generic: [
    "Oh, thank you so much for getting in touch, dear. I have to admit I'm a little confused by it all, my eyes aren't what they used to be and I've misplaced my glasses again. Could you explain it to me once more, nice and simply, from the start?",
    "Bless you for your patience with me. I do want to help, I just get in a muddle with these things and I like to be careful. Could you remind me which company you're from and how you got hold of my details?",
    "How kind of you to think of me. The trouble is I never make decisions in a hurry, my daughter is always telling me off for that. Would it be alright if I had a little think and asked my grandson when he next pops round?",
    "Oh dear, I'm not sure I quite follow, you'll have to bear with an old lady. Let me just fetch a pen and my notepad so I can write it all down properly. Now, what was it you needed me to do exactly?",
    "That's very interesting, thank you for letting me know. I do worry about getting things wrong at my age, so I hope you don't mind me asking a few silly questions first. Could you tell me again what this is all about?",
    "You've caught me just as I was putting the kettle on, dear. I'd love to help but I'm rather slow with anything to do with the computer or the bank. Is there perhaps a letter you could send me in the post so I can read it all properly?",
  ],
} as const;

export type Scenario = keyof typeof CANNED;
export const SCENARIOS = Object.keys(CANNED) as Scenario[];

export function pickCanned(scenario: Scenario, turn: number): string {
  const arr = CANNED[scenario] ?? CANNED.generic;
  return arr[Math.abs(turn) % arr.length];
}
